<?xml version="1.0"?>
<robot name="kobu" xmlns:xacro="http://ros.org/wiki/xacro">

  <!-- DEFINING GENERIC PROPERTIES THAT ARE USED IN THE XACRO FILE -->

  <!-- along x axis -->
  <xacro:property name="base_dia" value="0.5"/>
  <!-- along y axis -->
  <xacro:property name="base_dia" value="0.5"/>
  <!-- along z axis -->
  <xacro:property name="base_height" value="0.099"/>
  <xacro:property name="base_mass" value="50"/>
  <xacro:property name="wheel_dia" value="0.1"/>
  <xacro:property name="wheel_height" value="0.05"/>
  <xacro:property name="wheel_mass" value="0.5"/>

  <!-- COLOURS FOR MATERIAL -->
  <material name="white">
    <color rgba="1 1 1 1"/>
  </material>

  <material name="black">
    <color rgba ="0 0 0 1"/>
  </material>

  <material name="green">
    <color rgba="0 1 0 1"/>
  </material>

  <!-- MACROS FOR INERTIAL PROPERTIES -->
  <xacro:macro name="base_inertial">
    <inertial>
      <mass value="${base_mass}" />
      <inertia ixx="${(1/12)*base_mass*((base_dia*base_dia)+(base_height*base_height))}"
        ixy="0.0"
        ixz="0.0"
        iyy="${(1/12)*base_mass*((base_height*base_height)+(base_dia*base_dia))}"
        iyz="0.0"
        izz="${(1/12)*base_mass*((base_dia*base_dia)+(base_dia*base_dia))}" />
    </inertial>
  </xacro:macro>

  <xacro:macro name="wheel_inertial">
    <inertial>
      <mass value="${wheel_mass}" />
      <inertia ixx="1.0" ixy="0.0" ixz="0.0" iyy="1.0" iyz="0.0" izz="1.0" />
    </inertial>
  </xacro:macro>

  <!-- MACRO FOR GENERIC WHEEL. SUPPLY PARAMS TO PLACE THEM, JOINT INCLUDEDE IN MACRO -->
  <xacro:macro name="wheel" params="left_right rely">
    <link name="${left_right}_wheel">
      <visual>
        <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
        <geometry>
          <cylinder radius="${wheel_dia/2}" length="${wheel_height}"/>
        </geometry>
        <material name="black"/>
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
        <geometry>
          <cylinder radius="${wheel_dia/2}" length="${wheel_height}"/>
        </geometry>
      </collision>
      <xacro:wheel_inertial/>
    </link>

    <joint name="${left_right}_wheel_to_base_link" type="continuous">
      <origin xyz="0 ${rely*((base_dia/2+wheel_height/2))} ${wheel_dia/2}" rpy="0 0 0"/>
      <axis xyz="0 1 0" rpy="0 0 0"/>
      <parent link="base_link"/>
      <child link="${left_right}_wheel"/>
    </joint>
  </xacro:macro>

  <!-- DUMMY ROOT LINK SO THAT BASE LINK CAN BE GIVEN SOME MASS -->
  <link name="root_link"/>

  <!-- BASE LINK. MAIN BOX TO WHICH WHEEL AND EVERYTHING ELSE IS TO BE ATTACHED -->
  <link name="base_link">
    <visual>
      <origin xyz="0 0 ${wheel_dia/2}" rpy="0 0 0"/>
      <geometry>
        <cylinder length="${base_height}" radius="${base_dia/2}"/>
      </geometry>
      <material name="white"/>
    </visual>
    <collision name="base_link_collision">
      <origin xyz="0 0 ${wheel_dia/2}" rpy="0 0 0"/>
      <geometry>
        <cylinder length="${base_height}" radius="${base_dia/2}"/>
      </geometry>
    </collision>
    <xacro:base_inertial/>
  </link>

  <!-- CONNECT BASE LINK TO ROOT LINK -->
  <joint name="base_to_root_joint" type="fixed">
    <parent link="root_link"/>
    <child link="base_link"/>
  </joint>

  <!-- CREATING AN INSTANCE OF EACH WHEEL -->
  <xacro:wheel left_right="left" rely="1"/>
  <xacro:wheel left_right="right" rely="-1"/>

  <!--_______________________ Hokuyo Laser _______________________-->
  <link name="hokuyo_link">
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
    <box size="0.1 0.1 0.1"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <mesh filename="package://kobu_description/models/hokuyo.dae"/>
      </geometry>
    </visual>

    <inertial>
      <mass value="1e-5" />
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <inertia ixx="1e-6" ixy="0" ixz="0" iyy="1e-6" iyz="0" izz="1e-6" />
    </inertial>
  </link>

  <!--_______________________ Hokuyo Joint _______________________-->
  <joint name="hokuyo_joint" type="fixed">
    <axis xyz="0 1 0" />
    <origin xyz="0 0 ${wheel_dia+0.025}" rpy="0 0 0"/>
    <parent link="base_link"/>
    <child link="hokuyo_link"/>
  </joint>

  <!-- SKID STEER PLUGIN -->
  <gazebo>
    <plugin name="differential_drive_controller" filename="libgazebo_ros_diff_drive.so">
      <updateRate>100.0</updateRate>
      <robotNamespace></robotNamespace>
      <leftJoint>left_wheel_to_base_link</leftJoint>
      <rightJoint>right_wheel_to_base_link</rightJoint>
      <wheelSeparation>0.5</wheelSeparation>
      <wheelDiameter>0.1</wheelDiameter>
      <wheelAcceleration>1.0</wheelAcceleration>
      <wheelTorque>5</wheelTorque>
      <robotBaseFrame>base_link</robotBaseFrame>
      <commandTopic>cmd_vel</commandTopic>
      <odometryTopic>odom</odometryTopic>
      <broadcastTF>false</broadcastTF>
    </plugin>
  </gazebo>

  <!-- JOINT STATE PUBLISHER -->
  <gazebo>
    <plugin name="joint_state_publisher" filename="libgazebo_ros_joint_state_publisher.so">
      <jointName>left_wheel_to_base_link, right_wheel_to_base_link</jointName>
    </plugin>
  </gazebo>

</robot>
